version: "3.3"

services:
  observer:
    image: rchain/rnode:latest
    user: root
    networks:
      - rchain-net
    container_name: rnode.observer
    ports:
      - "40401:40401"
    command:
      [
        "run",
        "--bootstrap=rnode://5b0390a7c34319310de2432cc2c9dc433043783e@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--host=$READONLY_HOST",
        "--allow-private-addresses",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THREDHOLD",
      ]
    volumes:
      - ./data/observer:/var/lib/rnode/
      - ./conf/observer.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  rchain-net:
