version: "3.4"

services:
  observer:
    image: coop.rchain/rnode:latest
    user: root
    networks:
      - rchain-net
    container_name: rnode.observer
    ports:
      - 50400:50400
      - 50401:50401
      - 50402:50402
      - 50403:50403
      - 50404:50404
    command:
      [
        "run",
        "--bootstrap=rnode://5b0390a7c34319310de2432cc2c9dc433043783e@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--host=$OBSERVER_HOST",
        "--allow-private-addresses",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THRESHOLD",
      ]
    volumes:
      - ./data/$OBSERVER_HOST:/var/lib/rnode/
      - ./conf/observer/observer.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  rchain-net:
