servers:
  - bootstrap:
      host: rnode.bootstrap
      grpc_port: 40402
      http_port: 40403
  - validator1:
      host: rnode.validator1
      grpc_port: 40402
      http_port: 40403
  - validator2:
      host: rnode.validator2
      grpc_port: 40402
      http_port: 40403
waitTimeout: 300
waitInterval: 10
error_node_records: /error.txt
error_logs: /error.log
deploy:
  contract: /nil.rho
  phlo_limit: 100000
  phlo_price: 1
  deploy_key: 61e594124ca6af84a5468d98b34a4f3431ef39c54c6cf07fe6fbf8b079ef64f6
